name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install .[dev,docs]

      - name: Verify version tag matches project
        run: |
          python - <<'PY'
          import pathlib
          import tomllib

          tag = "${{ github.ref_name }}"
          if tag.startswith("v"):
              tag = tag[1:]

          data = tomllib.loads(pathlib.Path("pyproject.toml").read_text())
          project_version = data["project"]["version"]
          if project_version != tag:
              raise SystemExit(f"Tag {tag!r} does not match project version {project_version!r}")
          PY

      - name: Clean dist directory
        run: rm -rf dist/

      - name: Build distributions
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.9.0
        with:
          password: ${{ secrets.PYPI_TOKEN }}
